name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Репозиторыг татаж авах
      uses: actions/checkout@v4

    - name: C++ компайлер суулгах
      run: sudo apt update && sudo apt install -y g++ make

    - name: Кодыг хөрвүүлэх (Compile)
      run: g++ -o shapes main.cpp -lm

    - name: Програмыг ажиллуулах (Run)
      run: ./shapes
